<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.9" tiledversion="1.9.2" name="tileset" tilewidth="16" tileheight="16" tilecount="78" columns="13">
 <image source="tileset.png" width="208" height="96"/>
 <tile id="1" type="door"/>
 <tile id="2" type="obstacle"/>
 <tile id="3" type="obstacle"/>
 <tile id="4" type="obstacle"/>
 <tile id="5" type="obstacle"/>
 <tile id="6" type="obstacle"/>
 <tile id="8" type="door_left"/>
 <tile id="9" type="door_left"/>
 <tile id="10" type="obstacle"/>
 <tile id="11" type="obstacle"/>
 <tile id="12" type="obstacle"/>
 <tile id="14" type="door"/>
 <tile id="15" type="obstacle"/>
 <tile id="16" type="obstacle"/>
 <tile id="18" type="obstacle"/>
 <tile id="19" type="obstacle"/>
 <tile id="21" type="door_left"/>
 <tile id="22" type="door_left"/>
 <tile id="23" type="obstacle"/>
 <tile id="24" type="obstacle"/>
 <tile id="25" type="obstacle"/>
 <tile id="26" type="ladder"/>
 <tile id="27" type="ladder"/>
 <tile id="28" type="obstacle"/>
 <tile id="29" type="obstacle"/>
 <tile id="30" type="obstacle"/>
 <tile id="31" type="obstacle"/>
 <tile id="32" type="obstacle"/>
 <tile id="34" type="obstacle"/>
 <tile id="35" type="obstacle"/>
 <tile id="36" type="obstacle"/>
 <tile id="37" type="obstacle"/>
 <tile id="38" type="door_right"/>
 <tile id="39" type="ladder"/>
 <tile id="40" type="ladder"/>
 <tile id="41" type="obstacle"/>
 <tile id="42" type="obstacle"/>
 <tile id="43" type="obstacle"/>
 <tile id="44" type="obstacle"/>
 <tile id="45" type="obstacle"/>
 <tile id="47" type="obstacle"/>
 <tile id="48" type="obstacle"/>
 <tile id="49" type="obstacle"/>
 <tile id="50" type="obstacle"/>
 <tile id="51" type="door_right"/>
 <tile id="53" type="door"/>
 <tile id="58" type="obstacle"/>
 <tile id="60" type="obstacle"/>
 <tile id="61" type="obstacle"/>
 <tile id="63" type="obstacle"/>
 <tile id="64" type="door_right"/>
 <tile id="66" type="door"/>
 <tile id="67" type="obstacle_tv"/>
 <tile id="68" type="obstacle_tv"/>
 <tile id="70" type="obstacle"/>
 <tile id="71" type="obstacle"/>
 <tile id="72" type="obstacle"/>
 <tile id="77" type="door_right"/>
</tileset>
